name: lite_x
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.0.0
  font_awesome_flutter: ^10.12.0
  riverpod_annotation: ^3.0.0
  hive_ce: ^2.13.2
  hive_ce_flutter: ^2.3.2
  dio: ^5.9.0
  just_audio: ^0.10.5
  intl: ^0.20.2
  file_picker: ^10.3.3
  image_picker: ^1.2.0
  go_router: ^17.0.0
  uuid: ^4.5.1
  flutter_svg: ^2.2.1
  encrypt: ^5.0.3
  fpdart: ^1.1.1
  image: ^4.5.4
  visibility_detector: ^0.4.0+2
  url_launcher: ^6.3.2
  audio_waveforms: ^1.3.0
  emoji_picker_flutter: ^4.3.0
  cached_network_image: ^3.4.1
  timeago: ^3.7.1
  image_picker_for_web: ^3.1.0
  image_cropper: ^11.0.0
  path_provider: ^2.1.5
  html: ^0.15.6
  image_cropper_for_web: ^7.0.0
  dotted_border: ^3.1.0
  socket_io_client: ^3.1.2
  mockito: ^5.5.0
  chatview: ^2.5.0
  record: ^6.1.2
  flutter_dotenv: ^6.0.0
  connectivity_plus: ^7.0.0
  enough_giphy_flutter: ^0.4.2
  giphy_get: ^3.6.1+1
  material_design_icons_flutter: ^7.0.7296
  scrollable_positioned_list: ^0.3.8
  google_sign_in: ^6.2.1
  flutter_web_auth_2: ^4.1.0

  dartz: ^0.10.1

  readmore: 3.0.0

  provider:

  device_preview:
  top_snackbar_flutter: ^3.3.0

  intl_utils:
  firebase_core: ^4.2.0
  firebase_messaging: ^16.0.3

  lucide_icons_flutter: ^3.1.5
  webview_flutter: ^4.13.0
  flutter_inappwebview: ^6.1.5
  app_links: ^6.4.1

  share_plus: ^12.0.1
  fluttertoast: ^9.0.0
 # video_player: ^2.9.2

  http: any
  collection: any
  video_player: ^2.10.1
dev_dependencies:
  shared_preferences_platform_interface: ^2.3.0
  build_runner: ^2.7.1
  flutter_test:
    sdk: flutter
  hive_ce_generator: ^1.9.3
  riverpod_generator: ^3.0.0
  flutter_launcher_icons: ^0.14.4
  # For information on the generic Dart part of this file, see the
  # following page: https://dart.dev/tools/pub/pubspec

  # The following section is specific to Flutter packages.
  riverpod: any
  fake_async: ^1.3.3
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svg/
    - assets/images/
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

# Add this section at the bottom of pubspec.yaml
flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/xlogo.png" # Change this to the path of your icon
